### PR TITLE
Add Config Flow support

### PR DESCRIPTION
**Pull request by robert-alfaro**
Converted configuration to use Config Flow instead of YAML. Also moved away from needing to specify URL in favor of providing the `share_id` from the URL (the trailing portion).

### CODE REVIEW

**Comment by rsnodgrass** [comment]
Great changes!

However, can we make this a non-breaking change by continuing to support CONF_URL (if defined) instead of ONLY allowing share id? Then everyone who uses this doesn't have to manually go change when this is updated (especially if they have auto-updates setup on integrations and may not see the changelog).

We can leave the documentation showing only share id moving forward, but at least things won't break for people.

**Comment by rsnodgrass** [comment]
Thanks for cleaning up a few other things too!

**Comment by robert-alfaro** [comment]
I'm for backwards compatibility but unless I'm mistaken by moving away from yaml to config flow...that is a breaking change. I could be wrong but I'm thinking of several cases where I've had to manually remove the configuration.yaml text and re-setup via ui. It is because of this fact I decided to move to share id, and those users already have the share id, just need to copy paste into ui flow anew.

Thoughts?

**Comment by rsnodgrass** [comment]
Typically it seems well behaved integrations import the previous YAML
settings and save them as part of the config flow (e.g. importing existing
CONF_URL and stripping out the id), so it doesn't have to be re-entered.
Similarly, the config loading part of the integration falls back for some
period of time to using the old values (e.g. 6 months or a version bump or
two) before entirely removing the old YAML config as option. This minimizes
pain for users.

**Comment by robert-alfaro** [comment]
I guess I've not been fortunate to have experienced a well behaved migrating integration. Regardless sounds good... I'll look into it.

**Pull request merged**
